# Generated by Django 5.1.3 on 2025-11-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationCode',
        ),
    ]
