# Generated by Django 5.1.3 on 2025-11-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_delete_emailverificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='vitamin_c',
        ),
    ]
